# Generated by Django 4.2.4 on 2023-10-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=22)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_consulta', models.DateField()),
                ('data_criacao', models.DateField(auto_now=True)),
            ],
        ),
    ]
